create table mesto (
	id_mesto INT,
	nazev_mesta VARCHAR(50)
);
insert into mesto (id_mesto, nazev_mesta) values (1, 'Kadaka');
insert into mesto (id_mesto, nazev_mesta) values (2, 'Hasuda');
insert into mesto (id_mesto, nazev_mesta) values (3, 'Hengjing');
insert into mesto (id_mesto, nazev_mesta) values (4, 'Al Maḩjal');
insert into mesto (id_mesto, nazev_mesta) values (5, 'Belén');
insert into mesto (id_mesto, nazev_mesta) values (6, 'Castillos');
insert into mesto (id_mesto, nazev_mesta) values (7, 'Amouguer');
insert into mesto (id_mesto, nazev_mesta) values (8, 'Qiaole');
insert into mesto (id_mesto, nazev_mesta) values (9, 'Sabirabad');
insert into mesto (id_mesto, nazev_mesta) values (10, 'Oskarshamn');
insert into mesto (id_mesto, nazev_mesta) values (11, 'Cuenca');
insert into mesto (id_mesto, nazev_mesta) values (12, 'Marevo');
insert into mesto (id_mesto, nazev_mesta) values (13, 'Platagata');
insert into mesto (id_mesto, nazev_mesta) values (14, 'Ratenggoji');
insert into mesto (id_mesto, nazev_mesta) values (15, 'Gedera');
insert into mesto (id_mesto, nazev_mesta) values (16, 'Consuelo');
insert into mesto (id_mesto, nazev_mesta) values (17, 'Padhahegha');
insert into mesto (id_mesto, nazev_mesta) values (18, 'Svetlogorsk');
insert into mesto (id_mesto, nazev_mesta) values (19, 'Xinhua');
insert into mesto (id_mesto, nazev_mesta) values (20, 'Houzhen');
insert into mesto (id_mesto, nazev_mesta) values (21, 'Catanauan');
insert into mesto (id_mesto, nazev_mesta) values (22, 'Kupchino');
insert into mesto (id_mesto, nazev_mesta) values (23, 'Harderwijk');
insert into mesto (id_mesto, nazev_mesta) values (24, 'Tieremu');
insert into mesto (id_mesto, nazev_mesta) values (25, 'General La Madrid');
insert into mesto (id_mesto, nazev_mesta) values (26, 'Yicheng');
insert into mesto (id_mesto, nazev_mesta) values (27, 'Inkerman');
insert into mesto (id_mesto, nazev_mesta) values (28, 'Svyatogorsk');
insert into mesto (id_mesto, nazev_mesta) values (29, 'San José Acatempa');
insert into mesto (id_mesto, nazev_mesta) values (30, 'Taliouine');
insert into mesto (id_mesto, nazev_mesta) values (31, 'Keruguya');
insert into mesto (id_mesto, nazev_mesta) values (32, 'Strömsund');
insert into mesto (id_mesto, nazev_mesta) values (33, 'Lupo');
insert into mesto (id_mesto, nazev_mesta) values (34, 'Sabana de Parra');
insert into mesto (id_mesto, nazev_mesta) values (35, 'Duut');
insert into mesto (id_mesto, nazev_mesta) values (36, 'Quime');
insert into mesto (id_mesto, nazev_mesta) values (37, 'Changle');
insert into mesto (id_mesto, nazev_mesta) values (38, 'Ambatolampy');
insert into mesto (id_mesto, nazev_mesta) values (39, 'Ourtzagh');
insert into mesto (id_mesto, nazev_mesta) values (40, 'Saurama');
insert into mesto (id_mesto, nazev_mesta) values (41, 'Sai’erlong Xiang');
insert into mesto (id_mesto, nazev_mesta) values (42, 'Palaiochóri');
insert into mesto (id_mesto, nazev_mesta) values (43, 'Del Pilar');
insert into mesto (id_mesto, nazev_mesta) values (44, 'Sindangrasa');
insert into mesto (id_mesto, nazev_mesta) values (45, 'Yasynuvata');
insert into mesto (id_mesto, nazev_mesta) values (46, 'Aldeia do Bispo');
insert into mesto (id_mesto, nazev_mesta) values (47, 'Nanhai');
insert into mesto (id_mesto, nazev_mesta) values (48, 'Dole');
insert into mesto (id_mesto, nazev_mesta) values (49, 'Springfield');
insert into mesto (id_mesto, nazev_mesta) values (50, 'Puntaru');
insert into mesto (id_mesto, nazev_mesta) values (51, 'El Zapotal del Norte');
insert into mesto (id_mesto, nazev_mesta) values (52, 'Jinzhuang');
insert into mesto (id_mesto, nazev_mesta) values (53, 'Seseng');
insert into mesto (id_mesto, nazev_mesta) values (54, 'Sydney');
insert into mesto (id_mesto, nazev_mesta) values (55, 'Qixia');
insert into mesto (id_mesto, nazev_mesta) values (56, 'Itumbiara');
insert into mesto (id_mesto, nazev_mesta) values (57, 'Minneapolis');
insert into mesto (id_mesto, nazev_mesta) values (58, 'Gabú');
insert into mesto (id_mesto, nazev_mesta) values (59, 'Yangcun');
insert into mesto (id_mesto, nazev_mesta) values (60, 'San Enrique');
insert into mesto (id_mesto, nazev_mesta) values (61, 'Zhouyuan');
insert into mesto (id_mesto, nazev_mesta) values (62, 'Mkiriwadjumoi');
insert into mesto (id_mesto, nazev_mesta) values (63, 'Kazimierz Dolny');
insert into mesto (id_mesto, nazev_mesta) values (64, 'Aūa');
insert into mesto (id_mesto, nazev_mesta) values (65, 'Kabare');
insert into mesto (id_mesto, nazev_mesta) values (66, 'Kuala Terengganu');
insert into mesto (id_mesto, nazev_mesta) values (67, 'Palmas De Gran Canaria, Las');
insert into mesto (id_mesto, nazev_mesta) values (68, 'Murmuiža');
insert into mesto (id_mesto, nazev_mesta) values (69, 'Muzambinho');
insert into mesto (id_mesto, nazev_mesta) values (70, 'Yeniugou');
insert into mesto (id_mesto, nazev_mesta) values (71, 'Elías');
insert into mesto (id_mesto, nazev_mesta) values (72, 'Nāḩiyat Alī ash Sharqī');
insert into mesto (id_mesto, nazev_mesta) values (73, 'Koroyo');
insert into mesto (id_mesto, nazev_mesta) values (74, 'Xikou');
insert into mesto (id_mesto, nazev_mesta) values (75, 'Xiamao');
insert into mesto (id_mesto, nazev_mesta) values (76, 'Sarrat');
insert into mesto (id_mesto, nazev_mesta) values (77, 'Huashan');
insert into mesto (id_mesto, nazev_mesta) values (78, 'Labelle');
insert into mesto (id_mesto, nazev_mesta) values (79, 'Kista');
insert into mesto (id_mesto, nazev_mesta) values (80, 'Sukasada');
insert into mesto (id_mesto, nazev_mesta) values (81, 'Deshan');
insert into mesto (id_mesto, nazev_mesta) values (82, 'Totoras');
insert into mesto (id_mesto, nazev_mesta) values (83, 'Consolación del Sur');
insert into mesto (id_mesto, nazev_mesta) values (84, 'Messejana');
insert into mesto (id_mesto, nazev_mesta) values (85, '''Ali Sabieh');
insert into mesto (id_mesto, nazev_mesta) values (86, 'Gurinai');
insert into mesto (id_mesto, nazev_mesta) values (87, 'Duba-Yurt');
insert into mesto (id_mesto, nazev_mesta) values (88, 'Birmingham');
insert into mesto (id_mesto, nazev_mesta) values (89, 'Kayu Agung');
insert into mesto (id_mesto, nazev_mesta) values (90, 'Batticaloa');
insert into mesto (id_mesto, nazev_mesta) values (91, 'Gungguh');
insert into mesto (id_mesto, nazev_mesta) values (92, 'Juhaynah');
insert into mesto (id_mesto, nazev_mesta) values (93, 'Postřelmov');
insert into mesto (id_mesto, nazev_mesta) values (94, 'Lons-le-Saunier');
insert into mesto (id_mesto, nazev_mesta) values (95, 'Nagrog');
insert into mesto (id_mesto, nazev_mesta) values (96, 'Butwāl');
insert into mesto (id_mesto, nazev_mesta) values (97, 'Ji’ergele Teguoleng');
insert into mesto (id_mesto, nazev_mesta) values (98, 'Santa Cruz');
insert into mesto (id_mesto, nazev_mesta) values (99, 'Palmeira das Missões');
insert into mesto (id_mesto, nazev_mesta) values (100, 'Asan Kumbang');
insert into mesto (id_mesto, nazev_mesta) values (101, 'Cikuya');
insert into mesto (id_mesto, nazev_mesta) values (102, 'Lomintsevskiy');
insert into mesto (id_mesto, nazev_mesta) values (103, 'Guoxiang');
insert into mesto (id_mesto, nazev_mesta) values (104, 'Eybens');
insert into mesto (id_mesto, nazev_mesta) values (105, 'Hŭkkyo-ri');
insert into mesto (id_mesto, nazev_mesta) values (106, 'Chuoyuan');
insert into mesto (id_mesto, nazev_mesta) values (107, 'Gibbons');
insert into mesto (id_mesto, nazev_mesta) values (108, 'Orissaare');
insert into mesto (id_mesto, nazev_mesta) values (109, 'Varoška Rijeka');
insert into mesto (id_mesto, nazev_mesta) values (110, 'Warri');
insert into mesto (id_mesto, nazev_mesta) values (111, 'Dalarik');
insert into mesto (id_mesto, nazev_mesta) values (112, 'Sertânia');
insert into mesto (id_mesto, nazev_mesta) values (113, 'Taiobeiras');
insert into mesto (id_mesto, nazev_mesta) values (114, 'Ūdalah');
insert into mesto (id_mesto, nazev_mesta) values (115, 'Golubac');
insert into mesto (id_mesto, nazev_mesta) values (116, 'Gubo');
insert into mesto (id_mesto, nazev_mesta) values (117, 'Montes Velhos');
insert into mesto (id_mesto, nazev_mesta) values (118, 'Azogues');
insert into mesto (id_mesto, nazev_mesta) values (119, 'Stepnica');
insert into mesto (id_mesto, nazev_mesta) values (120, 'Gakem');
insert into mesto (id_mesto, nazev_mesta) values (121, 'Jeżów');
insert into mesto (id_mesto, nazev_mesta) values (122, 'Kuantan');
insert into mesto (id_mesto, nazev_mesta) values (123, 'Severo-Zadonsk');
insert into mesto (id_mesto, nazev_mesta) values (124, 'Sainte-Anne-des-Monts');
insert into mesto (id_mesto, nazev_mesta) values (125, 'Hendījān');
insert into mesto (id_mesto, nazev_mesta) values (126, 'Obrera');
insert into mesto (id_mesto, nazev_mesta) values (127, 'Laâyoune / El Aaiún');
insert into mesto (id_mesto, nazev_mesta) values (128, 'Bergem');
insert into mesto (id_mesto, nazev_mesta) values (129, 'Sainyabuli');
insert into mesto (id_mesto, nazev_mesta) values (130, 'Nakanojōmachi');
insert into mesto (id_mesto, nazev_mesta) values (131, 'Yunmeng Chengguanzhen');
insert into mesto (id_mesto, nazev_mesta) values (132, 'Arenas');
insert into mesto (id_mesto, nazev_mesta) values (133, 'Xinxiang');
insert into mesto (id_mesto, nazev_mesta) values (134, 'Karangasem');
insert into mesto (id_mesto, nazev_mesta) values (135, 'Cuauhtemoc');
insert into mesto (id_mesto, nazev_mesta) values (136, 'Rokycany');
insert into mesto (id_mesto, nazev_mesta) values (137, 'Mjölby');
insert into mesto (id_mesto, nazev_mesta) values (138, 'Xugu');
insert into mesto (id_mesto, nazev_mesta) values (139, 'Kaavi');
insert into mesto (id_mesto, nazev_mesta) values (140, 'Philadelphia');
insert into mesto (id_mesto, nazev_mesta) values (141, 'Mendes');
insert into mesto (id_mesto, nazev_mesta) values (142, 'Nysa');
insert into mesto (id_mesto, nazev_mesta) values (143, 'Maanas');
insert into mesto (id_mesto, nazev_mesta) values (144, 'Beutong Ateuh');
insert into mesto (id_mesto, nazev_mesta) values (145, 'Nguken');
insert into mesto (id_mesto, nazev_mesta) values (146, 'Praia Grande');
insert into mesto (id_mesto, nazev_mesta) values (147, 'Belozërskoye');
insert into mesto (id_mesto, nazev_mesta) values (148, 'Antequera');
insert into mesto (id_mesto, nazev_mesta) values (149, 'Wangfu');
insert into mesto (id_mesto, nazev_mesta) values (150, 'Kushk');
insert into mesto (id_mesto, nazev_mesta) values (151, 'Kastornoye');
insert into mesto (id_mesto, nazev_mesta) values (152, 'Votuporanga');
insert into mesto (id_mesto, nazev_mesta) values (153, 'Yaurisque');
insert into mesto (id_mesto, nazev_mesta) values (154, 'Chasŏng');
insert into mesto (id_mesto, nazev_mesta) values (155, 'Bato');
insert into mesto (id_mesto, nazev_mesta) values (156, 'Montenegro');
insert into mesto (id_mesto, nazev_mesta) values (157, 'Tanggungrejo');
insert into mesto (id_mesto, nazev_mesta) values (158, 'Bollnäs');
insert into mesto (id_mesto, nazev_mesta) values (159, 'Longkou');
insert into mesto (id_mesto, nazev_mesta) values (160, 'Municipio de Copacabana');
insert into mesto (id_mesto, nazev_mesta) values (161, 'Solntsevo');
insert into mesto (id_mesto, nazev_mesta) values (162, 'Tange Zhen');
insert into mesto (id_mesto, nazev_mesta) values (163, 'Örebro');
insert into mesto (id_mesto, nazev_mesta) values (164, 'Vorontsovka');
insert into mesto (id_mesto, nazev_mesta) values (165, 'Mehmand Chak');
insert into mesto (id_mesto, nazev_mesta) values (166, 'Boljevci');
insert into mesto (id_mesto, nazev_mesta) values (167, 'Mingyuedian');
insert into mesto (id_mesto, nazev_mesta) values (168, 'Gujiadian');
insert into mesto (id_mesto, nazev_mesta) values (169, 'Shizi');
insert into mesto (id_mesto, nazev_mesta) values (170, 'San Juan Bautista');
insert into mesto (id_mesto, nazev_mesta) values (171, 'Nanhe');
insert into mesto (id_mesto, nazev_mesta) values (172, 'Icononzo');
insert into mesto (id_mesto, nazev_mesta) values (173, 'Omaha');
insert into mesto (id_mesto, nazev_mesta) values (174, 'Shuanggang');
insert into mesto (id_mesto, nazev_mesta) values (175, 'Manghit');
insert into mesto (id_mesto, nazev_mesta) values (176, 'Dallas');
insert into mesto (id_mesto, nazev_mesta) values (177, 'Odolena Voda');
insert into mesto (id_mesto, nazev_mesta) values (178, 'Benito Juarez');
insert into mesto (id_mesto, nazev_mesta) values (179, 'Vershino-Shakhtaminskiy');
insert into mesto (id_mesto, nazev_mesta) values (180, 'Liuhu');
insert into mesto (id_mesto, nazev_mesta) values (181, 'Mensalong');
insert into mesto (id_mesto, nazev_mesta) values (182, 'Kalembutillu');
insert into mesto (id_mesto, nazev_mesta) values (183, 'Xitieshan');
insert into mesto (id_mesto, nazev_mesta) values (184, 'Jundian');
insert into mesto (id_mesto, nazev_mesta) values (185, 'Retenggoma');
insert into mesto (id_mesto, nazev_mesta) values (186, 'Guaíra');
insert into mesto (id_mesto, nazev_mesta) values (187, 'Haokou');
insert into mesto (id_mesto, nazev_mesta) values (188, 'Rancho Viejo');
insert into mesto (id_mesto, nazev_mesta) values (189, 'Boston');
insert into mesto (id_mesto, nazev_mesta) values (190, 'Sukamaju');
insert into mesto (id_mesto, nazev_mesta) values (191, 'Issa');
insert into mesto (id_mesto, nazev_mesta) values (192, 'Wierzawice');
insert into mesto (id_mesto, nazev_mesta) values (193, 'Bagacay');
insert into mesto (id_mesto, nazev_mesta) values (194, 'Ludgeřovice');
insert into mesto (id_mesto, nazev_mesta) values (195, 'Mari');
insert into mesto (id_mesto, nazev_mesta) values (196, 'Atafu Village');
insert into mesto (id_mesto, nazev_mesta) values (197, 'Kauhan');
insert into mesto (id_mesto, nazev_mesta) values (198, 'Campo de la Cruz');
insert into mesto (id_mesto, nazev_mesta) values (199, 'Ciudad Nueva');
insert into mesto (id_mesto, nazev_mesta) values (200, 'Rizómilos');
insert into mesto (id_mesto, nazev_mesta) values (201, 'Pomahuaca');
insert into mesto (id_mesto, nazev_mesta) values (202, 'Lila');
insert into mesto (id_mesto, nazev_mesta) values (203, 'Lishu');
insert into mesto (id_mesto, nazev_mesta) values (204, 'Longba');
insert into mesto (id_mesto, nazev_mesta) values (205, 'Segezha');
insert into mesto (id_mesto, nazev_mesta) values (206, 'Asker');
insert into mesto (id_mesto, nazev_mesta) values (207, 'Port Moody');
insert into mesto (id_mesto, nazev_mesta) values (208, 'Pamoyanan');
insert into mesto (id_mesto, nazev_mesta) values (209, 'Heishan');
insert into mesto (id_mesto, nazev_mesta) values (210, 'Vân Canh');
insert into mesto (id_mesto, nazev_mesta) values (211, 'Diapaga');
insert into mesto (id_mesto, nazev_mesta) values (212, 'Sirinhaém');
insert into mesto (id_mesto, nazev_mesta) values (213, 'Stara Błotnica');
insert into mesto (id_mesto, nazev_mesta) values (214, 'Arari');
insert into mesto (id_mesto, nazev_mesta) values (215, 'Hetang');
insert into mesto (id_mesto, nazev_mesta) values (216, 'Nazyvayevsk');
insert into mesto (id_mesto, nazev_mesta) values (217, 'Beskolen');
insert into mesto (id_mesto, nazev_mesta) values (218, 'Gangshangji');
insert into mesto (id_mesto, nazev_mesta) values (219, 'Mirnyy');
insert into mesto (id_mesto, nazev_mesta) values (220, 'Yerba Buena');
insert into mesto (id_mesto, nazev_mesta) values (221, 'Kovilj');
insert into mesto (id_mesto, nazev_mesta) values (222, 'Luanda');
insert into mesto (id_mesto, nazev_mesta) values (223, 'Oesena');
insert into mesto (id_mesto, nazev_mesta) values (224, 'Zemun');
insert into mesto (id_mesto, nazev_mesta) values (225, 'Jingmen');
insert into mesto (id_mesto, nazev_mesta) values (226, 'Krasyliv');
insert into mesto (id_mesto, nazev_mesta) values (227, 'Uthai Thani');
insert into mesto (id_mesto, nazev_mesta) values (228, 'Nossa Senhora de Machede');
insert into mesto (id_mesto, nazev_mesta) values (229, 'Duntou');
insert into mesto (id_mesto, nazev_mesta) values (230, 'Shibetsu');
insert into mesto (id_mesto, nazev_mesta) values (231, 'Mohelnice');
insert into mesto (id_mesto, nazev_mesta) values (232, 'Baofeng');
insert into mesto (id_mesto, nazev_mesta) values (233, 'Kamennogorsk');
insert into mesto (id_mesto, nazev_mesta) values (234, 'Igreja');
insert into mesto (id_mesto, nazev_mesta) values (235, 'Hengxizhen');
insert into mesto (id_mesto, nazev_mesta) values (236, 'Sumberejo');
insert into mesto (id_mesto, nazev_mesta) values (237, 'Yajiang');
insert into mesto (id_mesto, nazev_mesta) values (238, 'Aduo');
insert into mesto (id_mesto, nazev_mesta) values (239, 'Shīrvān');
insert into mesto (id_mesto, nazev_mesta) values (240, 'Kabalo');
insert into mesto (id_mesto, nazev_mesta) values (241, 'Kudamatsu');
insert into mesto (id_mesto, nazev_mesta) values (242, 'António Enes');
insert into mesto (id_mesto, nazev_mesta) values (243, 'Karatsu');
insert into mesto (id_mesto, nazev_mesta) values (244, 'Penedono');
insert into mesto (id_mesto, nazev_mesta) values (245, 'Longjiang');
insert into mesto (id_mesto, nazev_mesta) values (246, 'Funabashi');
insert into mesto (id_mesto, nazev_mesta) values (247, 'Aemura');
insert into mesto (id_mesto, nazev_mesta) values (248, 'Banjar Penyalin');
insert into mesto (id_mesto, nazev_mesta) values (249, 'Conselheiro Lafaiete');
insert into mesto (id_mesto, nazev_mesta) values (250, 'Qohord-e Bālā');
insert into mesto (id_mesto, nazev_mesta) values (251, 'Umm Ruwaba');
insert into mesto (id_mesto, nazev_mesta) values (252, 'Andahuaylillas');
insert into mesto (id_mesto, nazev_mesta) values (253, 'Sasovo');
insert into mesto (id_mesto, nazev_mesta) values (254, 'Askim');
insert into mesto (id_mesto, nazev_mesta) values (255, 'Balakhta');
insert into mesto (id_mesto, nazev_mesta) values (256, 'Phra Yuen');
insert into mesto (id_mesto, nazev_mesta) values (257, 'Caicun');
insert into mesto (id_mesto, nazev_mesta) values (258, 'Tsaghveri');
insert into mesto (id_mesto, nazev_mesta) values (259, 'Getengan');
insert into mesto (id_mesto, nazev_mesta) values (260, 'Santa Barbara');
insert into mesto (id_mesto, nazev_mesta) values (261, 'Al Buţayḩah');
insert into mesto (id_mesto, nazev_mesta) values (262, 'Žrnovo');
insert into mesto (id_mesto, nazev_mesta) values (263, 'Hostos');
insert into mesto (id_mesto, nazev_mesta) values (264, 'Metu');
insert into mesto (id_mesto, nazev_mesta) values (265, 'Syrskoye');
insert into mesto (id_mesto, nazev_mesta) values (266, 'Göteborg');
insert into mesto (id_mesto, nazev_mesta) values (267, 'Chigorodó');
insert into mesto (id_mesto, nazev_mesta) values (268, 'Turki');
insert into mesto (id_mesto, nazev_mesta) values (269, 'Skelivka');
insert into mesto (id_mesto, nazev_mesta) values (270, 'Paris 10');
insert into mesto (id_mesto, nazev_mesta) values (271, 'Vidovci');
insert into mesto (id_mesto, nazev_mesta) values (272, 'Liyang');
insert into mesto (id_mesto, nazev_mesta) values (273, 'La Virgen');
insert into mesto (id_mesto, nazev_mesta) values (274, 'Patos Fshat');
insert into mesto (id_mesto, nazev_mesta) values (275, 'Staraya Stanitsa');
insert into mesto (id_mesto, nazev_mesta) values (276, 'Fovissste');
insert into mesto (id_mesto, nazev_mesta) values (277, 'Vårby');
insert into mesto (id_mesto, nazev_mesta) values (278, 'Niquinohomo');
insert into mesto (id_mesto, nazev_mesta) values (279, 'Noyon');
insert into mesto (id_mesto, nazev_mesta) values (280, 'Linxia Chengguanzhen');
insert into mesto (id_mesto, nazev_mesta) values (281, 'El Calvario');
insert into mesto (id_mesto, nazev_mesta) values (282, 'Gulod');
insert into mesto (id_mesto, nazev_mesta) values (283, 'Canhas');
insert into mesto (id_mesto, nazev_mesta) values (284, 'Buga');
insert into mesto (id_mesto, nazev_mesta) values (285, 'Toulon');
insert into mesto (id_mesto, nazev_mesta) values (286, 'Songying');
insert into mesto (id_mesto, nazev_mesta) values (287, 'Salam');
insert into mesto (id_mesto, nazev_mesta) values (288, 'Nobo');
insert into mesto (id_mesto, nazev_mesta) values (289, 'Lyamino');
insert into mesto (id_mesto, nazev_mesta) values (290, 'Grenoble');
insert into mesto (id_mesto, nazev_mesta) values (291, 'Anyama');
insert into mesto (id_mesto, nazev_mesta) values (292, 'Pare');
insert into mesto (id_mesto, nazev_mesta) values (293, 'Tengqiao');
insert into mesto (id_mesto, nazev_mesta) values (294, 'Daoukro');
insert into mesto (id_mesto, nazev_mesta) values (295, 'Machida');
insert into mesto (id_mesto, nazev_mesta) values (296, 'Tharyarwady');
insert into mesto (id_mesto, nazev_mesta) values (297, 'Usquil');
insert into mesto (id_mesto, nazev_mesta) values (298, 'Periyiáli');
insert into mesto (id_mesto, nazev_mesta) values (299, 'Leskovac');
insert into mesto (id_mesto, nazev_mesta) values (300, 'Chuoyuan');
insert into mesto (id_mesto, nazev_mesta) values (301, 'Wuhao');
insert into mesto (id_mesto, nazev_mesta) values (302, 'Avarua');
insert into mesto (id_mesto, nazev_mesta) values (303, 'Paris 13');
insert into mesto (id_mesto, nazev_mesta) values (304, 'Portelinha');
insert into mesto (id_mesto, nazev_mesta) values (305, 'Čortanovci');
insert into mesto (id_mesto, nazev_mesta) values (306, 'San Juan de Manapiare');
insert into mesto (id_mesto, nazev_mesta) values (307, 'Karatau');
insert into mesto (id_mesto, nazev_mesta) values (308, 'Linoan');
insert into mesto (id_mesto, nazev_mesta) values (309, 'Zhouyuan');
insert into mesto (id_mesto, nazev_mesta) values (310, 'Raminho');
insert into mesto (id_mesto, nazev_mesta) values (311, 'Jiachuan');
insert into mesto (id_mesto, nazev_mesta) values (312, 'San Enrique');
insert into mesto (id_mesto, nazev_mesta) values (313, 'Safed');
insert into mesto (id_mesto, nazev_mesta) values (314, 'Bangker');
insert into mesto (id_mesto, nazev_mesta) values (315, 'Qorashina');
insert into mesto (id_mesto, nazev_mesta) values (316, 'Rizal');
insert into mesto (id_mesto, nazev_mesta) values (317, 'Amboise');
insert into mesto (id_mesto, nazev_mesta) values (318, 'Carthage');
insert into mesto (id_mesto, nazev_mesta) values (319, 'Kampánis');
insert into mesto (id_mesto, nazev_mesta) values (320, 'Karonga');
insert into mesto (id_mesto, nazev_mesta) values (321, 'Daxi');
insert into mesto (id_mesto, nazev_mesta) values (322, 'Banghai');
insert into mesto (id_mesto, nazev_mesta) values (323, 'Chilecito');
insert into mesto (id_mesto, nazev_mesta) values (324, 'Helsingborg');
insert into mesto (id_mesto, nazev_mesta) values (325, 'Alangalang');
insert into mesto (id_mesto, nazev_mesta) values (326, 'Kiryū');
insert into mesto (id_mesto, nazev_mesta) values (327, 'Kwangju');
insert into mesto (id_mesto, nazev_mesta) values (328, 'Cubará');
insert into mesto (id_mesto, nazev_mesta) values (329, 'Mê Linh');
insert into mesto (id_mesto, nazev_mesta) values (330, 'Bol');
insert into mesto (id_mesto, nazev_mesta) values (331, 'Acajutla');
insert into mesto (id_mesto, nazev_mesta) values (332, 'Batakte');
insert into mesto (id_mesto, nazev_mesta) values (333, 'Baleagung');
insert into mesto (id_mesto, nazev_mesta) values (334, 'Socota');
insert into mesto (id_mesto, nazev_mesta) values (335, 'Gulod');
insert into mesto (id_mesto, nazev_mesta) values (336, 'Xiaoyue');
insert into mesto (id_mesto, nazev_mesta) values (337, 'Lichinga');
insert into mesto (id_mesto, nazev_mesta) values (338, 'Az Zuwaytīnah');
insert into mesto (id_mesto, nazev_mesta) values (339, 'Fukagawa');
insert into mesto (id_mesto, nazev_mesta) values (340, 'Verkhovyna');
insert into mesto (id_mesto, nazev_mesta) values (341, 'Santa Cruz do Capibaribe');
insert into mesto (id_mesto, nazev_mesta) values (342, 'Kérkyra');
insert into mesto (id_mesto, nazev_mesta) values (343, 'Beixiaoying');
insert into mesto (id_mesto, nazev_mesta) values (344, 'Chicago');
insert into mesto (id_mesto, nazev_mesta) values (345, 'Zhangdu');
insert into mesto (id_mesto, nazev_mesta) values (346, 'Balogo');
insert into mesto (id_mesto, nazev_mesta) values (347, 'Mama');
insert into mesto (id_mesto, nazev_mesta) values (348, 'Angered');
insert into mesto (id_mesto, nazev_mesta) values (349, 'Luna');
insert into mesto (id_mesto, nazev_mesta) values (350, 'Jiulong');
insert into mesto (id_mesto, nazev_mesta) values (351, 'Bataiporã');
insert into mesto (id_mesto, nazev_mesta) values (352, 'Changfeng');
insert into mesto (id_mesto, nazev_mesta) values (353, 'Barueri');
insert into mesto (id_mesto, nazev_mesta) values (354, 'Prochnookopskaya');
insert into mesto (id_mesto, nazev_mesta) values (355, 'Leijiadian');
insert into mesto (id_mesto, nazev_mesta) values (356, 'Soraya');
insert into mesto (id_mesto, nazev_mesta) values (357, 'Ban Selaphum');
insert into mesto (id_mesto, nazev_mesta) values (358, 'Ncue');
insert into mesto (id_mesto, nazev_mesta) values (359, 'Mporokoso');
insert into mesto (id_mesto, nazev_mesta) values (360, 'Krajan Battal');
insert into mesto (id_mesto, nazev_mesta) values (361, 'Yanjiang');
insert into mesto (id_mesto, nazev_mesta) values (362, 'Palencia');
insert into mesto (id_mesto, nazev_mesta) values (363, 'Bitung');
insert into mesto (id_mesto, nazev_mesta) values (364, 'Schellenberg');
insert into mesto (id_mesto, nazev_mesta) values (365, 'Karangmulya');
insert into mesto (id_mesto, nazev_mesta) values (366, 'Sidi Yahia el Gharb');
insert into mesto (id_mesto, nazev_mesta) values (367, 'Chalamarca');
insert into mesto (id_mesto, nazev_mesta) values (368, 'Zhendong');
insert into mesto (id_mesto, nazev_mesta) values (369, 'Monasterevin');
insert into mesto (id_mesto, nazev_mesta) values (370, 'Kostelec nad Černými Lesy');
insert into mesto (id_mesto, nazev_mesta) values (371, 'Froly');
insert into mesto (id_mesto, nazev_mesta) values (372, 'Al Jamīmah');
insert into mesto (id_mesto, nazev_mesta) values (373, 'Huangzhan');
insert into mesto (id_mesto, nazev_mesta) values (374, 'Baolong');
insert into mesto (id_mesto, nazev_mesta) values (375, 'Novohrad-Volyns’kyy');
insert into mesto (id_mesto, nazev_mesta) values (376, 'Olyshivka');
insert into mesto (id_mesto, nazev_mesta) values (377, 'Tourcoing');
insert into mesto (id_mesto, nazev_mesta) values (378, 'Perlez');
insert into mesto (id_mesto, nazev_mesta) values (379, 'Miaoshi');
insert into mesto (id_mesto, nazev_mesta) values (380, 'Nyagla');
insert into mesto (id_mesto, nazev_mesta) values (381, 'Gyumri');
insert into mesto (id_mesto, nazev_mesta) values (382, 'Anping');
insert into mesto (id_mesto, nazev_mesta) values (383, 'Czarna');
insert into mesto (id_mesto, nazev_mesta) values (384, 'Gribanovskiy');
insert into mesto (id_mesto, nazev_mesta) values (385, 'Ndom');
insert into mesto (id_mesto, nazev_mesta) values (386, 'Santiago De Compostela');
insert into mesto (id_mesto, nazev_mesta) values (387, 'Wum');
insert into mesto (id_mesto, nazev_mesta) values (388, 'Jiaocheng');
insert into mesto (id_mesto, nazev_mesta) values (389, 'Badulla');
insert into mesto (id_mesto, nazev_mesta) values (390, 'Karafao');
insert into mesto (id_mesto, nazev_mesta) values (391, 'Caleta Cruz');
insert into mesto (id_mesto, nazev_mesta) values (392, 'Vilarinho das Cambas');
insert into mesto (id_mesto, nazev_mesta) values (393, 'Wapno');
insert into mesto (id_mesto, nazev_mesta) values (394, 'Calaba');
insert into mesto (id_mesto, nazev_mesta) values (395, 'Beaune');
insert into mesto (id_mesto, nazev_mesta) values (396, 'Gyumri');
insert into mesto (id_mesto, nazev_mesta) values (397, 'Sydney');
insert into mesto (id_mesto, nazev_mesta) values (398, 'Kushtia');
insert into mesto (id_mesto, nazev_mesta) values (399, 'San Nicolás');
insert into mesto (id_mesto, nazev_mesta) values (400, 'Marquard');
insert into mesto (id_mesto, nazev_mesta) values (401, 'Majan');
insert into mesto (id_mesto, nazev_mesta) values (402, 'Měnín');
insert into mesto (id_mesto, nazev_mesta) values (403, 'Si Prachan');
insert into mesto (id_mesto, nazev_mesta) values (404, 'Jacksonville');
insert into mesto (id_mesto, nazev_mesta) values (405, 'Combita');
insert into mesto (id_mesto, nazev_mesta) values (406, 'Paseyan');
insert into mesto (id_mesto, nazev_mesta) values (407, 'Yaodu');
insert into mesto (id_mesto, nazev_mesta) values (408, 'Meaux');
insert into mesto (id_mesto, nazev_mesta) values (409, 'Mahekou');
insert into mesto (id_mesto, nazev_mesta) values (410, 'São João dos Montes');
insert into mesto (id_mesto, nazev_mesta) values (411, 'Kurzętnik');
insert into mesto (id_mesto, nazev_mesta) values (412, 'Plaški');
insert into mesto (id_mesto, nazev_mesta) values (413, 'Dom Pedro');
insert into mesto (id_mesto, nazev_mesta) values (414, 'Otaniemi');
insert into mesto (id_mesto, nazev_mesta) values (415, 'Delingha');
insert into mesto (id_mesto, nazev_mesta) values (416, 'Cové');
insert into mesto (id_mesto, nazev_mesta) values (417, 'Nomhon');
insert into mesto (id_mesto, nazev_mesta) values (418, 'Kitsuki');
insert into mesto (id_mesto, nazev_mesta) values (419, 'Michałów-Reginów');
insert into mesto (id_mesto, nazev_mesta) values (420, 'Eṭ Ṭaiyiba');
insert into mesto (id_mesto, nazev_mesta) values (421, 'Norrtälje');
insert into mesto (id_mesto, nazev_mesta) values (422, 'Tongzi');
insert into mesto (id_mesto, nazev_mesta) values (423, 'Tengqiao');
insert into mesto (id_mesto, nazev_mesta) values (424, 'Dzüünharaa');
insert into mesto (id_mesto, nazev_mesta) values (425, 'Tenkodogo');
insert into mesto (id_mesto, nazev_mesta) values (426, 'Santa Cruz');
insert into mesto (id_mesto, nazev_mesta) values (427, 'Boli');
insert into mesto (id_mesto, nazev_mesta) values (428, 'Ouzini');
insert into mesto (id_mesto, nazev_mesta) values (429, 'Shāhdādkot');
insert into mesto (id_mesto, nazev_mesta) values (430, 'Paris La Défense');
insert into mesto (id_mesto, nazev_mesta) values (431, 'Balyqshy');
insert into mesto (id_mesto, nazev_mesta) values (432, 'Mayanhe');
insert into mesto (id_mesto, nazev_mesta) values (433, 'Jalasenga');
insert into mesto (id_mesto, nazev_mesta) values (434, 'Malakwal City');
insert into mesto (id_mesto, nazev_mesta) values (435, 'Kerrobert');
insert into mesto (id_mesto, nazev_mesta) values (436, 'Pasirjaya');
insert into mesto (id_mesto, nazev_mesta) values (437, 'Qaţanah');
insert into mesto (id_mesto, nazev_mesta) values (438, 'Dalsjöfors');
insert into mesto (id_mesto, nazev_mesta) values (439, 'Sara Kunda');
insert into mesto (id_mesto, nazev_mesta) values (440, 'Ngrayun');
insert into mesto (id_mesto, nazev_mesta) values (441, 'Nice');
insert into mesto (id_mesto, nazev_mesta) values (442, 'Ngedhusuba');
insert into mesto (id_mesto, nazev_mesta) values (443, 'Jishui');
insert into mesto (id_mesto, nazev_mesta) values (444, 'Salaya');
insert into mesto (id_mesto, nazev_mesta) values (445, 'Mizur');
insert into mesto (id_mesto, nazev_mesta) values (446, 'Washington');
insert into mesto (id_mesto, nazev_mesta) values (447, 'Magdalena');
insert into mesto (id_mesto, nazev_mesta) values (448, 'Praia Grande');
insert into mesto (id_mesto, nazev_mesta) values (449, 'Yangjiaqiao');
insert into mesto (id_mesto, nazev_mesta) values (450, 'Sendangagung');
insert into mesto (id_mesto, nazev_mesta) values (451, 'Qitan');
insert into mesto (id_mesto, nazev_mesta) values (452, 'Xiabeisi');
insert into mesto (id_mesto, nazev_mesta) values (453, 'Le Mans');
insert into mesto (id_mesto, nazev_mesta) values (454, 'Jinji');
insert into mesto (id_mesto, nazev_mesta) values (455, 'Novogornyy');
insert into mesto (id_mesto, nazev_mesta) values (456, 'Gorzyce');
insert into mesto (id_mesto, nazev_mesta) values (457, 'Xiangdong');
insert into mesto (id_mesto, nazev_mesta) values (458, 'Damaishan');
insert into mesto (id_mesto, nazev_mesta) values (459, 'Dongjiao');
insert into mesto (id_mesto, nazev_mesta) values (460, 'Maliiha');
insert into mesto (id_mesto, nazev_mesta) values (461, 'San Antonio Oeste');
insert into mesto (id_mesto, nazev_mesta) values (462, 'Villa Mercedes');
insert into mesto (id_mesto, nazev_mesta) values (463, 'Cagbang');
insert into mesto (id_mesto, nazev_mesta) values (464, 'Samburat');
insert into mesto (id_mesto, nazev_mesta) values (465, 'Alfenas');
insert into mesto (id_mesto, nazev_mesta) values (466, 'Xiaopu');
insert into mesto (id_mesto, nazev_mesta) values (467, 'Sierpc');
insert into mesto (id_mesto, nazev_mesta) values (468, 'Puyang');
insert into mesto (id_mesto, nazev_mesta) values (469, '‘Alāqahdārī Kirān wa Munjān');
insert into mesto (id_mesto, nazev_mesta) values (470, 'Morani');
insert into mesto (id_mesto, nazev_mesta) values (471, 'Pengbu');
insert into mesto (id_mesto, nazev_mesta) values (472, 'Kolomanu');
insert into mesto (id_mesto, nazev_mesta) values (473, 'Linpu');
insert into mesto (id_mesto, nazev_mesta) values (474, 'Guwoterus');
insert into mesto (id_mesto, nazev_mesta) values (475, 'Boyle');
insert into mesto (id_mesto, nazev_mesta) values (476, 'Ujung');
insert into mesto (id_mesto, nazev_mesta) values (477, 'Dayu');
insert into mesto (id_mesto, nazev_mesta) values (478, 'Milwaukee');
insert into mesto (id_mesto, nazev_mesta) values (479, 'Sembung');
insert into mesto (id_mesto, nazev_mesta) values (480, 'Peraía');
insert into mesto (id_mesto, nazev_mesta) values (481, 'Staten Island');
insert into mesto (id_mesto, nazev_mesta) values (482, 'Mercedes');
insert into mesto (id_mesto, nazev_mesta) values (483, 'Jiangchuanlu');
insert into mesto (id_mesto, nazev_mesta) values (484, 'Nemby');
insert into mesto (id_mesto, nazev_mesta) values (485, 'Choa Saidān Shāh');
insert into mesto (id_mesto, nazev_mesta) values (486, 'Bankim');
insert into mesto (id_mesto, nazev_mesta) values (487, 'Szeged');
insert into mesto (id_mesto, nazev_mesta) values (488, 'Zombo');
insert into mesto (id_mesto, nazev_mesta) values (489, 'Milwaukee');
insert into mesto (id_mesto, nazev_mesta) values (490, 'Vuhlehirs’k');
insert into mesto (id_mesto, nazev_mesta) values (491, 'Colesberg');
insert into mesto (id_mesto, nazev_mesta) values (492, 'Jumpangdua');
insert into mesto (id_mesto, nazev_mesta) values (493, 'Palma De Mallorca');
insert into mesto (id_mesto, nazev_mesta) values (494, 'Yasenevo');
insert into mesto (id_mesto, nazev_mesta) values (495, 'Zishan');
insert into mesto (id_mesto, nazev_mesta) values (496, 'Fovissste');
insert into mesto (id_mesto, nazev_mesta) values (497, 'Damiao');
insert into mesto (id_mesto, nazev_mesta) values (498, 'Botigues');
insert into mesto (id_mesto, nazev_mesta) values (499, 'Lysyanka');
insert into mesto (id_mesto, nazev_mesta) values (500, 'Hujirt');
insert into mesto (id_mesto, nazev_mesta) values (501, 'Novi Beograd');
insert into mesto (id_mesto, nazev_mesta) values (502, 'Arţās');
insert into mesto (id_mesto, nazev_mesta) values (503, 'Osiedle-Nowiny');
insert into mesto (id_mesto, nazev_mesta) values (504, 'Balete');
insert into mesto (id_mesto, nazev_mesta) values (505, 'Milaor');
insert into mesto (id_mesto, nazev_mesta) values (506, 'Kobarid');
insert into mesto (id_mesto, nazev_mesta) values (507, 'Gandzak');
insert into mesto (id_mesto, nazev_mesta) values (508, 'Shuanglong');
insert into mesto (id_mesto, nazev_mesta) values (509, 'Bamenda');
insert into mesto (id_mesto, nazev_mesta) values (510, 'El Monte');
insert into mesto (id_mesto, nazev_mesta) values (511, 'Bantarpanjang');
insert into mesto (id_mesto, nazev_mesta) values (512, 'Ilama');
insert into mesto (id_mesto, nazev_mesta) values (513, 'Taverny');
insert into mesto (id_mesto, nazev_mesta) values (514, 'Kotlovka');
insert into mesto (id_mesto, nazev_mesta) values (515, 'Gobernador Costa');
insert into mesto (id_mesto, nazev_mesta) values (516, 'Brooklyn');
insert into mesto (id_mesto, nazev_mesta) values (517, 'Tulung');
insert into mesto (id_mesto, nazev_mesta) values (518, 'Qırmızı Samux');
insert into mesto (id_mesto, nazev_mesta) values (519, 'Canchayllo');
insert into mesto (id_mesto, nazev_mesta) values (520, 'Birao');
insert into mesto (id_mesto, nazev_mesta) values (521, 'Zaoshi');
insert into mesto (id_mesto, nazev_mesta) values (522, 'Caujul');
insert into mesto (id_mesto, nazev_mesta) values (523, 'Horní Bříza');
insert into mesto (id_mesto, nazev_mesta) values (524, 'Ronggo');
insert into mesto (id_mesto, nazev_mesta) values (525, 'Vihāri');
insert into mesto (id_mesto, nazev_mesta) values (526, 'Saint-Jérôme');
insert into mesto (id_mesto, nazev_mesta) values (527, 'Guapi');
insert into mesto (id_mesto, nazev_mesta) values (528, 'Joaquín V. González');
insert into mesto (id_mesto, nazev_mesta) values (529, 'Parigi');
insert into mesto (id_mesto, nazev_mesta) values (530, 'Norabats’');
insert into mesto (id_mesto, nazev_mesta) values (531, 'Jaboatão');
insert into mesto (id_mesto, nazev_mesta) values (532, 'Ruyigi');
insert into mesto (id_mesto, nazev_mesta) values (533, 'Jaro');
insert into mesto (id_mesto, nazev_mesta) values (534, 'Qaffīn');
insert into mesto (id_mesto, nazev_mesta) values (535, 'Drawsko');
insert into mesto (id_mesto, nazev_mesta) values (536, 'Omboué');
insert into mesto (id_mesto, nazev_mesta) values (537, 'Chroustovice');
insert into mesto (id_mesto, nazev_mesta) values (538, 'Tukbur');
insert into mesto (id_mesto, nazev_mesta) values (539, 'Meghrashen');
insert into mesto (id_mesto, nazev_mesta) values (540, 'Ikaalinen');
insert into mesto (id_mesto, nazev_mesta) values (541, 'Miaoling');
insert into mesto (id_mesto, nazev_mesta) values (542, 'Zhulin');
insert into mesto (id_mesto, nazev_mesta) values (543, 'Shahre Jadide Andisheh');
insert into mesto (id_mesto, nazev_mesta) values (544, 'Punta Alta');
insert into mesto (id_mesto, nazev_mesta) values (545, 'Kagawasan');
insert into mesto (id_mesto, nazev_mesta) values (546, 'Hepingyizu');
insert into mesto (id_mesto, nazev_mesta) values (547, 'Ubá');
insert into mesto (id_mesto, nazev_mesta) values (548, 'Basel');
insert into mesto (id_mesto, nazev_mesta) values (549, 'Igreja');
insert into mesto (id_mesto, nazev_mesta) values (550, 'Rude');
insert into mesto (id_mesto, nazev_mesta) values (551, 'Oak Bay');
insert into mesto (id_mesto, nazev_mesta) values (552, 'Berezovo');
insert into mesto (id_mesto, nazev_mesta) values (553, 'Trabulheira');
insert into mesto (id_mesto, nazev_mesta) values (554, 'Wangda');
insert into mesto (id_mesto, nazev_mesta) values (555, 'Mirebalais');
insert into mesto (id_mesto, nazev_mesta) values (556, 'Nicoya');
insert into mesto (id_mesto, nazev_mesta) values (557, 'Ninghai');
insert into mesto (id_mesto, nazev_mesta) values (558, 'Northern Suburbs Mc');
insert into mesto (id_mesto, nazev_mesta) values (559, 'Dongkengkou');
insert into mesto (id_mesto, nazev_mesta) values (560, 'Nukuoro');
insert into mesto (id_mesto, nazev_mesta) values (561, 'Koatas Lao');
insert into mesto (id_mesto, nazev_mesta) values (562, 'Klagen');
insert into mesto (id_mesto, nazev_mesta) values (563, 'Olivia');
insert into mesto (id_mesto, nazev_mesta) values (564, 'Beidajie');
insert into mesto (id_mesto, nazev_mesta) values (565, 'Patrocínio');
insert into mesto (id_mesto, nazev_mesta) values (566, 'Zlatar');
insert into mesto (id_mesto, nazev_mesta) values (567, 'Jdaidet el Matn');
insert into mesto (id_mesto, nazev_mesta) values (568, 'Puerto Varas');
insert into mesto (id_mesto, nazev_mesta) values (569, 'Šmartno pri Litiji');
insert into mesto (id_mesto, nazev_mesta) values (570, 'Tianjiazhuang');
insert into mesto (id_mesto, nazev_mesta) values (571, 'Mount Frere');
insert into mesto (id_mesto, nazev_mesta) values (572, 'Ponyri Vtoryye');
insert into mesto (id_mesto, nazev_mesta) values (573, 'Curahpacul Satu');
insert into mesto (id_mesto, nazev_mesta) values (574, 'Benito Juarez');
insert into mesto (id_mesto, nazev_mesta) values (575, 'Duli');
insert into mesto (id_mesto, nazev_mesta) values (576, 'Ngala');
insert into mesto (id_mesto, nazev_mesta) values (577, 'Tidili Mesfioua');
insert into mesto (id_mesto, nazev_mesta) values (578, 'Jingzhou');
insert into mesto (id_mesto, nazev_mesta) values (579, 'Oslo');
insert into mesto (id_mesto, nazev_mesta) values (580, 'Lendava');
insert into mesto (id_mesto, nazev_mesta) values (581, 'Balatun');
insert into mesto (id_mesto, nazev_mesta) values (582, 'Jacksonville');
insert into mesto (id_mesto, nazev_mesta) values (583, 'Pomerode');
insert into mesto (id_mesto, nazev_mesta) values (584, 'Cihaladan');
insert into mesto (id_mesto, nazev_mesta) values (585, 'San Martín');
insert into mesto (id_mesto, nazev_mesta) values (586, 'Manacsac');
insert into mesto (id_mesto, nazev_mesta) values (587, 'Janeng');
insert into mesto (id_mesto, nazev_mesta) values (588, 'Mache');
insert into mesto (id_mesto, nazev_mesta) values (589, 'Kout na Šumavě');
insert into mesto (id_mesto, nazev_mesta) values (590, 'Nizhnevartovsk');
insert into mesto (id_mesto, nazev_mesta) values (591, 'Gaïtánion');
insert into mesto (id_mesto, nazev_mesta) values (592, 'Muesanaik');
insert into mesto (id_mesto, nazev_mesta) values (593, 'Takayama');
insert into mesto (id_mesto, nazev_mesta) values (594, 'Ouro Preto do Oeste');
insert into mesto (id_mesto, nazev_mesta) values (595, 'Toki');
insert into mesto (id_mesto, nazev_mesta) values (596, 'Beicang');
insert into mesto (id_mesto, nazev_mesta) values (597, 'Takedamachi');
insert into mesto (id_mesto, nazev_mesta) values (598, 'Okhtyrka');
insert into mesto (id_mesto, nazev_mesta) values (599, 'Ménaka');
insert into mesto (id_mesto, nazev_mesta) values (600, 'Złoczew');
insert into mesto (id_mesto, nazev_mesta) values (601, 'Berón de Astrada');
insert into mesto (id_mesto, nazev_mesta) values (602, 'Guocun');
insert into mesto (id_mesto, nazev_mesta) values (603, 'Sirib');
insert into mesto (id_mesto, nazev_mesta) values (604, 'Dawangzhuang');
insert into mesto (id_mesto, nazev_mesta) values (605, 'Kawengan');
insert into mesto (id_mesto, nazev_mesta) values (606, 'Guarda Nova');
insert into mesto (id_mesto, nazev_mesta) values (607, 'Faraulep');
insert into mesto (id_mesto, nazev_mesta) values (608, 'Fátima');
insert into mesto (id_mesto, nazev_mesta) values (609, 'Jenzan');
insert into mesto (id_mesto, nazev_mesta) values (610, 'Ijuw');
insert into mesto (id_mesto, nazev_mesta) values (611, 'Tanggul Wetan');
insert into mesto (id_mesto, nazev_mesta) values (612, 'Manjakandriana');
insert into mesto (id_mesto, nazev_mesta) values (613, 'Calamba');
insert into mesto (id_mesto, nazev_mesta) values (614, 'Caen');
insert into mesto (id_mesto, nazev_mesta) values (615, 'Náousa');
insert into mesto (id_mesto, nazev_mesta) values (616, 'Vakhtan');
insert into mesto (id_mesto, nazev_mesta) values (617, 'Idah');
insert into mesto (id_mesto, nazev_mesta) values (618, 'Dian-ay');
insert into mesto (id_mesto, nazev_mesta) values (619, 'Canguaretama');
insert into mesto (id_mesto, nazev_mesta) values (620, 'Verin Artashat');
insert into mesto (id_mesto, nazev_mesta) values (621, 'San Antonio');
insert into mesto (id_mesto, nazev_mesta) values (622, 'San Antonio');
insert into mesto (id_mesto, nazev_mesta) values (623, 'Manola');
insert into mesto (id_mesto, nazev_mesta) values (624, 'Kokubunji');
insert into mesto (id_mesto, nazev_mesta) values (625, 'Del Rosario');
insert into mesto (id_mesto, nazev_mesta) values (626, 'Takikawa');
insert into mesto (id_mesto, nazev_mesta) values (627, 'Nanger');
insert into mesto (id_mesto, nazev_mesta) values (628, 'Mladá Boleslav');
insert into mesto (id_mesto, nazev_mesta) values (629, 'Obispos');
insert into mesto (id_mesto, nazev_mesta) values (630, 'Pasarkuok');
insert into mesto (id_mesto, nazev_mesta) values (631, 'Raojān');
insert into mesto (id_mesto, nazev_mesta) values (632, 'Wengtian');
insert into mesto (id_mesto, nazev_mesta) values (633, 'Chalon-sur-Saône');
insert into mesto (id_mesto, nazev_mesta) values (634, 'Lyubimets');
insert into mesto (id_mesto, nazev_mesta) values (635, 'Baranoa');
insert into mesto (id_mesto, nazev_mesta) values (636, 'Bălţi');
insert into mesto (id_mesto, nazev_mesta) values (637, 'Poddębice');
insert into mesto (id_mesto, nazev_mesta) values (638, 'Pantai Ceuremen');
insert into mesto (id_mesto, nazev_mesta) values (639, 'Trảng Bàng');
insert into mesto (id_mesto, nazev_mesta) values (640, 'Nyaungdon');
insert into mesto (id_mesto, nazev_mesta) values (641, 'Huité');
insert into mesto (id_mesto, nazev_mesta) values (642, 'Bairro de Santo António');
insert into mesto (id_mesto, nazev_mesta) values (643, 'Ansan-si');
insert into mesto (id_mesto, nazev_mesta) values (644, 'Guacarí');
insert into mesto (id_mesto, nazev_mesta) values (645, 'Imulolong');
insert into mesto (id_mesto, nazev_mesta) values (646, 'Muleng');
insert into mesto (id_mesto, nazev_mesta) values (647, 'Truskolasy');
insert into mesto (id_mesto, nazev_mesta) values (648, 'Krzemieniewo');
insert into mesto (id_mesto, nazev_mesta) values (649, 'San Jacinto');
insert into mesto (id_mesto, nazev_mesta) values (650, 'Dongtian');
insert into mesto (id_mesto, nazev_mesta) values (651, 'Heimahe');
insert into mesto (id_mesto, nazev_mesta) values (652, 'Gashua');
insert into mesto (id_mesto, nazev_mesta) values (653, 'Gaoling');
insert into mesto (id_mesto, nazev_mesta) values (654, 'Myasnikyan');
insert into mesto (id_mesto, nazev_mesta) values (655, 'Wilwerwiltz');
insert into mesto (id_mesto, nazev_mesta) values (656, 'Paris 18');
insert into mesto (id_mesto, nazev_mesta) values (657, 'Guanjiabao');
insert into mesto (id_mesto, nazev_mesta) values (658, 'San Antonio Oeste');
insert into mesto (id_mesto, nazev_mesta) values (659, 'Yushikalasu');
insert into mesto (id_mesto, nazev_mesta) values (660, 'Gourma Rharous');
insert into mesto (id_mesto, nazev_mesta) values (661, 'Kerep Wetan');
insert into mesto (id_mesto, nazev_mesta) values (662, 'Dao');
insert into mesto (id_mesto, nazev_mesta) values (663, 'Xianglong');
insert into mesto (id_mesto, nazev_mesta) values (664, 'El Limon');
insert into mesto (id_mesto, nazev_mesta) values (665, 'Fucheng');
insert into mesto (id_mesto, nazev_mesta) values (666, 'São José dos Pinhais');
insert into mesto (id_mesto, nazev_mesta) values (667, 'Bucu Kidul');
insert into mesto (id_mesto, nazev_mesta) values (668, 'Al Fayyūm');
insert into mesto (id_mesto, nazev_mesta) values (669, 'Katav-Ivanovsk');
insert into mesto (id_mesto, nazev_mesta) values (670, 'Argalastí');
insert into mesto (id_mesto, nazev_mesta) values (671, 'Volary');
insert into mesto (id_mesto, nazev_mesta) values (672, 'Choma');
insert into mesto (id_mesto, nazev_mesta) values (673, 'Mirebalais');
insert into mesto (id_mesto, nazev_mesta) values (674, 'Klek');
insert into mesto (id_mesto, nazev_mesta) values (675, 'Denton');
insert into mesto (id_mesto, nazev_mesta) values (676, 'Leeuwarden');
insert into mesto (id_mesto, nazev_mesta) values (677, 'Zaječí');
insert into mesto (id_mesto, nazev_mesta) values (678, 'Panjakent');
insert into mesto (id_mesto, nazev_mesta) values (679, 'Gengzhuang');
insert into mesto (id_mesto, nazev_mesta) values (680, 'Orlando');
insert into mesto (id_mesto, nazev_mesta) values (681, 'Darband');
insert into mesto (id_mesto, nazev_mesta) values (682, 'Azara');
insert into mesto (id_mesto, nazev_mesta) values (683, 'Śliwice');
insert into mesto (id_mesto, nazev_mesta) values (684, 'Saint Paul');
insert into mesto (id_mesto, nazev_mesta) values (685, 'Sumy');
insert into mesto (id_mesto, nazev_mesta) values (686, 'Ban Huai Thalaeng');
insert into mesto (id_mesto, nazev_mesta) values (687, 'Nanding');
insert into mesto (id_mesto, nazev_mesta) values (688, 'Bonsari');
insert into mesto (id_mesto, nazev_mesta) values (689, 'Uyen Hung');
insert into mesto (id_mesto, nazev_mesta) values (690, 'Bobigny');
insert into mesto (id_mesto, nazev_mesta) values (691, 'Orenburg');
insert into mesto (id_mesto, nazev_mesta) values (692, 'Guoyuan');
insert into mesto (id_mesto, nazev_mesta) values (693, 'Chalon-sur-Saône');
insert into mesto (id_mesto, nazev_mesta) values (694, 'Höganäs');
insert into mesto (id_mesto, nazev_mesta) values (695, 'Kirs');
insert into mesto (id_mesto, nazev_mesta) values (696, 'Biscucuy');
insert into mesto (id_mesto, nazev_mesta) values (697, 'Tsushima');
insert into mesto (id_mesto, nazev_mesta) values (698, 'Benito Juarez');
insert into mesto (id_mesto, nazev_mesta) values (699, 'Xiangshun');
insert into mesto (id_mesto, nazev_mesta) values (700, 'Hołoby');
insert into mesto (id_mesto, nazev_mesta) values (701, 'Cigadung');
insert into mesto (id_mesto, nazev_mesta) values (702, 'Tirlyanskiy');
insert into mesto (id_mesto, nazev_mesta) values (703, 'Milltown');
insert into mesto (id_mesto, nazev_mesta) values (704, 'Surubim');
insert into mesto (id_mesto, nazev_mesta) values (705, 'Māmu Kānjan');
insert into mesto (id_mesto, nazev_mesta) values (706, 'Rosetta');
insert into mesto (id_mesto, nazev_mesta) values (707, 'Margen');
insert into mesto (id_mesto, nazev_mesta) values (708, 'Eira Nova');
insert into mesto (id_mesto, nazev_mesta) values (709, 'Shimen');
insert into mesto (id_mesto, nazev_mesta) values (710, 'Lalauigan');
insert into mesto (id_mesto, nazev_mesta) values (711, 'Kotri');
insert into mesto (id_mesto, nazev_mesta) values (712, 'Bungu');
insert into mesto (id_mesto, nazev_mesta) values (713, 'Perístasi');
insert into mesto (id_mesto, nazev_mesta) values (714, 'Nglego');
insert into mesto (id_mesto, nazev_mesta) values (715, 'Wujiayao');
insert into mesto (id_mesto, nazev_mesta) values (716, 'Krajan Baru');
insert into mesto (id_mesto, nazev_mesta) values (717, 'Nanterre');
insert into mesto (id_mesto, nazev_mesta) values (718, 'Pasir');
insert into mesto (id_mesto, nazev_mesta) values (719, 'Qingzhou');
insert into mesto (id_mesto, nazev_mesta) values (720, 'New York City');
insert into mesto (id_mesto, nazev_mesta) values (721, 'Santa Rita Aplaya');
insert into mesto (id_mesto, nazev_mesta) values (722, 'Diré');
insert into mesto (id_mesto, nazev_mesta) values (723, 'Alindao');
insert into mesto (id_mesto, nazev_mesta) values (724, 'Tô Hạp');
insert into mesto (id_mesto, nazev_mesta) values (725, 'Curahnongko');
insert into mesto (id_mesto, nazev_mesta) values (726, 'Uvarovo');
insert into mesto (id_mesto, nazev_mesta) values (727, 'Karavan');
insert into mesto (id_mesto, nazev_mesta) values (728, 'Sangumata');
insert into mesto (id_mesto, nazev_mesta) values (729, 'Sieniawa Żarska');
insert into mesto (id_mesto, nazev_mesta) values (730, 'Kawasaki');
insert into mesto (id_mesto, nazev_mesta) values (731, 'Mazatenango');
insert into mesto (id_mesto, nazev_mesta) values (732, 'Takahata');
insert into mesto (id_mesto, nazev_mesta) values (733, 'Berezayka');
insert into mesto (id_mesto, nazev_mesta) values (734, 'Kraslice');
insert into mesto (id_mesto, nazev_mesta) values (735, 'Pamplona/Iruña');
insert into mesto (id_mesto, nazev_mesta) values (736, 'Golem');
insert into mesto (id_mesto, nazev_mesta) values (737, 'Usman’');
insert into mesto (id_mesto, nazev_mesta) values (738, 'Perpignan');
insert into mesto (id_mesto, nazev_mesta) values (739, 'Jönköping');
insert into mesto (id_mesto, nazev_mesta) values (740, 'Kampokpok');
insert into mesto (id_mesto, nazev_mesta) values (741, 'Talabaan');
insert into mesto (id_mesto, nazev_mesta) values (742, 'Rumburk');
insert into mesto (id_mesto, nazev_mesta) values (743, 'Sơn Tịnh');
insert into mesto (id_mesto, nazev_mesta) values (744, 'Bergen');
insert into mesto (id_mesto, nazev_mesta) values (745, 'Wróblew');
insert into mesto (id_mesto, nazev_mesta) values (746, 'Kotido');
insert into mesto (id_mesto, nazev_mesta) values (747, 'Mobile');
insert into mesto (id_mesto, nazev_mesta) values (748, 'Gävle');
insert into mesto (id_mesto, nazev_mesta) values (749, 'São Marcos da Serra');
insert into mesto (id_mesto, nazev_mesta) values (750, 'Tiztoutine');
insert into mesto (id_mesto, nazev_mesta) values (751, 'Dhuusamarreeb');
insert into mesto (id_mesto, nazev_mesta) values (752, 'Bakau');
insert into mesto (id_mesto, nazev_mesta) values (753, 'San Cristóbal');
insert into mesto (id_mesto, nazev_mesta) values (754, 'Vallauris');
insert into mesto (id_mesto, nazev_mesta) values (755, 'Xuefu');
insert into mesto (id_mesto, nazev_mesta) values (756, 'Ceerigaabo');
insert into mesto (id_mesto, nazev_mesta) values (757, 'Koudougou');
insert into mesto (id_mesto, nazev_mesta) values (758, 'Helsingborg');
insert into mesto (id_mesto, nazev_mesta) values (759, 'Carthage');
insert into mesto (id_mesto, nazev_mesta) values (760, 'Colonia Wanda');
insert into mesto (id_mesto, nazev_mesta) values (761, 'Guápiles');
insert into mesto (id_mesto, nazev_mesta) values (762, 'Potolo');
insert into mesto (id_mesto, nazev_mesta) values (763, 'Vihāri');
insert into mesto (id_mesto, nazev_mesta) values (764, 'Souto');
insert into mesto (id_mesto, nazev_mesta) values (765, 'Barrosa');
insert into mesto (id_mesto, nazev_mesta) values (766, 'Santa Cruz La Laguna');
insert into mesto (id_mesto, nazev_mesta) values (767, 'Cícero Dantas');
insert into mesto (id_mesto, nazev_mesta) values (768, 'Jinsha');
insert into mesto (id_mesto, nazev_mesta) values (769, 'Gesikan');
insert into mesto (id_mesto, nazev_mesta) values (770, 'Zuocun');
insert into mesto (id_mesto, nazev_mesta) values (771, 'Miami Beach');
insert into mesto (id_mesto, nazev_mesta) values (772, 'Yujia');
insert into mesto (id_mesto, nazev_mesta) values (773, 'Bến Tre');
insert into mesto (id_mesto, nazev_mesta) values (774, 'Azurva');
insert into mesto (id_mesto, nazev_mesta) values (775, 'Dolní Bojanovice');
insert into mesto (id_mesto, nazev_mesta) values (776, 'Yarmolyntsi');
insert into mesto (id_mesto, nazev_mesta) values (777, 'Verkhnyaya Belka');
insert into mesto (id_mesto, nazev_mesta) values (778, 'Cumming');
insert into mesto (id_mesto, nazev_mesta) values (779, 'Niš');
insert into mesto (id_mesto, nazev_mesta) values (780, 'Sumberpitu');
insert into mesto (id_mesto, nazev_mesta) values (781, 'Jackson');
insert into mesto (id_mesto, nazev_mesta) values (782, 'Labuan');
insert into mesto (id_mesto, nazev_mesta) values (783, 'Suai');
insert into mesto (id_mesto, nazev_mesta) values (784, 'Nol');
insert into mesto (id_mesto, nazev_mesta) values (785, 'Tô Hạp');
insert into mesto (id_mesto, nazev_mesta) values (786, 'Tagakpan');
insert into mesto (id_mesto, nazev_mesta) values (787, 'Shuntian');
insert into mesto (id_mesto, nazev_mesta) values (788, 'Jincheng');
insert into mesto (id_mesto, nazev_mesta) values (789, 'Wyszogród');
insert into mesto (id_mesto, nazev_mesta) values (790, 'Saint-Marcellin');
insert into mesto (id_mesto, nazev_mesta) values (791, 'Guaíba');
insert into mesto (id_mesto, nazev_mesta) values (792, 'La Cesira');
insert into mesto (id_mesto, nazev_mesta) values (793, 'Laguna');
insert into mesto (id_mesto, nazev_mesta) values (794, 'Mogoditshane');
insert into mesto (id_mesto, nazev_mesta) values (795, 'Daxin');
insert into mesto (id_mesto, nazev_mesta) values (796, 'Zhaozhen');
insert into mesto (id_mesto, nazev_mesta) values (797, 'Bunog');
insert into mesto (id_mesto, nazev_mesta) values (798, 'Orguz');
insert into mesto (id_mesto, nazev_mesta) values (799, 'Aibura');
insert into mesto (id_mesto, nazev_mesta) values (800, 'Bełżec');
insert into mesto (id_mesto, nazev_mesta) values (801, 'Rancabugel');
insert into mesto (id_mesto, nazev_mesta) values (802, 'Wenjiao');
insert into mesto (id_mesto, nazev_mesta) values (803, 'Novorossiysk');
insert into mesto (id_mesto, nazev_mesta) values (804, 'Jaworze');
insert into mesto (id_mesto, nazev_mesta) values (805, 'Volzhskiy');
insert into mesto (id_mesto, nazev_mesta) values (806, 'Beylagan');
insert into mesto (id_mesto, nazev_mesta) values (807, 'Bang Phae');
insert into mesto (id_mesto, nazev_mesta) values (808, 'Yangxu');
insert into mesto (id_mesto, nazev_mesta) values (809, 'Dobrovo');
insert into mesto (id_mesto, nazev_mesta) values (810, 'Yangambi');
insert into mesto (id_mesto, nazev_mesta) values (811, 'Xianlin');
insert into mesto (id_mesto, nazev_mesta) values (812, 'Kilindoni');
insert into mesto (id_mesto, nazev_mesta) values (813, 'Kraśnik');
insert into mesto (id_mesto, nazev_mesta) values (814, 'Várzea de Sintra');
insert into mesto (id_mesto, nazev_mesta) values (815, 'Zhangye');
insert into mesto (id_mesto, nazev_mesta) values (816, 'Kobylí');
insert into mesto (id_mesto, nazev_mesta) values (817, 'Vypolzovo');
insert into mesto (id_mesto, nazev_mesta) values (818, 'Baiyin');
insert into mesto (id_mesto, nazev_mesta) values (819, 'Kalianda');
insert into mesto (id_mesto, nazev_mesta) values (820, 'Antabamba');
insert into mesto (id_mesto, nazev_mesta) values (821, 'Presidente Médici');
insert into mesto (id_mesto, nazev_mesta) values (822, 'Marks');
insert into mesto (id_mesto, nazev_mesta) values (823, 'Terawas');
insert into mesto (id_mesto, nazev_mesta) values (824, 'Yurla');
insert into mesto (id_mesto, nazev_mesta) values (825, 'Hekou');
insert into mesto (id_mesto, nazev_mesta) values (826, 'Obong');
insert into mesto (id_mesto, nazev_mesta) values (827, 'Qiaozhuang');
insert into mesto (id_mesto, nazev_mesta) values (828, 'Bendilmuning');
insert into mesto (id_mesto, nazev_mesta) values (829, 'Obock');
insert into mesto (id_mesto, nazev_mesta) values (830, 'Hortolândia');
insert into mesto (id_mesto, nazev_mesta) values (831, 'Xinming');
insert into mesto (id_mesto, nazev_mesta) values (832, 'Blois');
insert into mesto (id_mesto, nazev_mesta) values (833, 'São Domingos do Maranhão');
insert into mesto (id_mesto, nazev_mesta) values (834, 'São Manços');
insert into mesto (id_mesto, nazev_mesta) values (835, 'Blumenau');
insert into mesto (id_mesto, nazev_mesta) values (836, 'Nagato');
insert into mesto (id_mesto, nazev_mesta) values (837, 'Ugljevik');
insert into mesto (id_mesto, nazev_mesta) values (838, 'Arma');
insert into mesto (id_mesto, nazev_mesta) values (839, 'Querocotillo');
insert into mesto (id_mesto, nazev_mesta) values (840, 'Kashira');
insert into mesto (id_mesto, nazev_mesta) values (841, 'Kalianda');
insert into mesto (id_mesto, nazev_mesta) values (842, 'Baomin');
insert into mesto (id_mesto, nazev_mesta) values (843, 'Polonnaruwa');
insert into mesto (id_mesto, nazev_mesta) values (844, 'Dijon');
insert into mesto (id_mesto, nazev_mesta) values (845, 'Qijia');
insert into mesto (id_mesto, nazev_mesta) values (846, 'Sremčica');
insert into mesto (id_mesto, nazev_mesta) values (847, 'Baylo');
insert into mesto (id_mesto, nazev_mesta) values (848, 'Inhumas');
insert into mesto (id_mesto, nazev_mesta) values (849, 'Bachok');
insert into mesto (id_mesto, nazev_mesta) values (850, 'Wang’er');
insert into mesto (id_mesto, nazev_mesta) values (851, 'Pa Tio');
insert into mesto (id_mesto, nazev_mesta) values (852, 'San Pablo');
insert into mesto (id_mesto, nazev_mesta) values (853, 'Ban Thai Tan');
insert into mesto (id_mesto, nazev_mesta) values (854, 'Zubrzyca Dolna');
insert into mesto (id_mesto, nazev_mesta) values (855, 'Ma’an');
insert into mesto (id_mesto, nazev_mesta) values (856, 'Ikar');
insert into mesto (id_mesto, nazev_mesta) values (857, 'Kuangsan');
insert into mesto (id_mesto, nazev_mesta) values (858, 'Ramalhal');
insert into mesto (id_mesto, nazev_mesta) values (859, 'Rizal');
insert into mesto (id_mesto, nazev_mesta) values (860, 'Wrocław');
insert into mesto (id_mesto, nazev_mesta) values (861, 'Fengmu');
insert into mesto (id_mesto, nazev_mesta) values (862, 'Ābyek');
insert into mesto (id_mesto, nazev_mesta) values (863, 'Loen');
insert into mesto (id_mesto, nazev_mesta) values (864, 'Āsasa');
insert into mesto (id_mesto, nazev_mesta) values (865, 'Datuan');
insert into mesto (id_mesto, nazev_mesta) values (866, 'Casablanca');
insert into mesto (id_mesto, nazev_mesta) values (867, 'Tamanan');
insert into mesto (id_mesto, nazev_mesta) values (868, 'Maddela');
insert into mesto (id_mesto, nazev_mesta) values (869, 'Beijós');
insert into mesto (id_mesto, nazev_mesta) values (870, 'Bahía Honda');
insert into mesto (id_mesto, nazev_mesta) values (871, 'Valerik');
insert into mesto (id_mesto, nazev_mesta) values (872, 'Tambo');
insert into mesto (id_mesto, nazev_mesta) values (873, 'Sainte-Adèle');
insert into mesto (id_mesto, nazev_mesta) values (874, 'Sinamar');
insert into mesto (id_mesto, nazev_mesta) values (875, 'Vogar');
insert into mesto (id_mesto, nazev_mesta) values (876, 'San Justo');
insert into mesto (id_mesto, nazev_mesta) values (877, 'Hradec Králové');
insert into mesto (id_mesto, nazev_mesta) values (878, 'Świecie');
insert into mesto (id_mesto, nazev_mesta) values (879, 'Ialoveni');
insert into mesto (id_mesto, nazev_mesta) values (880, 'Zhouwang');
insert into mesto (id_mesto, nazev_mesta) values (881, 'Wąsosz');
insert into mesto (id_mesto, nazev_mesta) values (882, 'Oyabe');
insert into mesto (id_mesto, nazev_mesta) values (883, 'Vahdat');
insert into mesto (id_mesto, nazev_mesta) values (884, 'San Rafael');
insert into mesto (id_mesto, nazev_mesta) values (885, 'Mpulungu');
insert into mesto (id_mesto, nazev_mesta) values (886, 'Chodzież');
insert into mesto (id_mesto, nazev_mesta) values (887, 'Pathum Rat');
insert into mesto (id_mesto, nazev_mesta) values (888, 'Melbourne');
insert into mesto (id_mesto, nazev_mesta) values (889, 'Mashava');
insert into mesto (id_mesto, nazev_mesta) values (890, 'Ban Mai');
insert into mesto (id_mesto, nazev_mesta) values (891, 'Rudky');
insert into mesto (id_mesto, nazev_mesta) values (892, 'Groningen');
insert into mesto (id_mesto, nazev_mesta) values (893, 'Kurba');
insert into mesto (id_mesto, nazev_mesta) values (894, 'Tembau');
insert into mesto (id_mesto, nazev_mesta) values (895, 'Obrera');
insert into mesto (id_mesto, nazev_mesta) values (896, 'Strasbourg');
insert into mesto (id_mesto, nazev_mesta) values (897, 'Altıağac');
insert into mesto (id_mesto, nazev_mesta) values (898, 'Betio Village');
insert into mesto (id_mesto, nazev_mesta) values (899, 'Bagnères-de-Bigorre');
insert into mesto (id_mesto, nazev_mesta) values (900, 'Pindi Gheb');
insert into mesto (id_mesto, nazev_mesta) values (901, 'Huangshi');
insert into mesto (id_mesto, nazev_mesta) values (902, 'Lidingö');
insert into mesto (id_mesto, nazev_mesta) values (903, 'Chorente');
insert into mesto (id_mesto, nazev_mesta) values (904, 'Shuangfeng');
insert into mesto (id_mesto, nazev_mesta) values (905, 'Umeå');
insert into mesto (id_mesto, nazev_mesta) values (906, 'Kolobovo');
insert into mesto (id_mesto, nazev_mesta) values (907, 'Yên Bái');
insert into mesto (id_mesto, nazev_mesta) values (908, 'Mumias');
insert into mesto (id_mesto, nazev_mesta) values (909, 'Chabu');
insert into mesto (id_mesto, nazev_mesta) values (910, 'Stryszów');
insert into mesto (id_mesto, nazev_mesta) values (911, 'Campok');
insert into mesto (id_mesto, nazev_mesta) values (912, 'Tzaneen');
insert into mesto (id_mesto, nazev_mesta) values (913, 'Hongxingqiao');
insert into mesto (id_mesto, nazev_mesta) values (914, 'Huangxikou');
insert into mesto (id_mesto, nazev_mesta) values (915, 'Örebro');
insert into mesto (id_mesto, nazev_mesta) values (916, 'Paatan');
insert into mesto (id_mesto, nazev_mesta) values (917, 'Jinshan');
insert into mesto (id_mesto, nazev_mesta) values (918, 'Kuala Bhee');
insert into mesto (id_mesto, nazev_mesta) values (919, 'Evansville');
insert into mesto (id_mesto, nazev_mesta) values (920, 'Eastern Suburbs Mc');
insert into mesto (id_mesto, nazev_mesta) values (921, 'Hodkovičky');
insert into mesto (id_mesto, nazev_mesta) values (922, 'Tecka');
insert into mesto (id_mesto, nazev_mesta) values (923, 'Korosten’');
insert into mesto (id_mesto, nazev_mesta) values (924, 'Yungaisi');
insert into mesto (id_mesto, nazev_mesta) values (925, 'Acton Vale');
insert into mesto (id_mesto, nazev_mesta) values (926, 'Maicao');
insert into mesto (id_mesto, nazev_mesta) values (927, 'Macapsing');
insert into mesto (id_mesto, nazev_mesta) values (928, 'Wafang');
insert into mesto (id_mesto, nazev_mesta) values (929, 'Bunutan');
insert into mesto (id_mesto, nazev_mesta) values (930, 'Sakado');
insert into mesto (id_mesto, nazev_mesta) values (931, 'Kouvarás');
insert into mesto (id_mesto, nazev_mesta) values (932, 'Safakulevo');
insert into mesto (id_mesto, nazev_mesta) values (933, 'Las Palmas');
insert into mesto (id_mesto, nazev_mesta) values (934, 'Włosienica');
insert into mesto (id_mesto, nazev_mesta) values (935, 'Cimaung Kidul');
insert into mesto (id_mesto, nazev_mesta) values (936, 'Volodymyrets’');
insert into mesto (id_mesto, nazev_mesta) values (937, 'Maganha');
insert into mesto (id_mesto, nazev_mesta) values (938, 'Jurovski Dol');
insert into mesto (id_mesto, nazev_mesta) values (939, 'Santo André');
insert into mesto (id_mesto, nazev_mesta) values (940, 'Nikol’sk');
insert into mesto (id_mesto, nazev_mesta) values (941, 'Chagoda');
insert into mesto (id_mesto, nazev_mesta) values (942, 'San Rafael');
insert into mesto (id_mesto, nazev_mesta) values (943, 'Hrob');
insert into mesto (id_mesto, nazev_mesta) values (944, 'Houston');
insert into mesto (id_mesto, nazev_mesta) values (945, 'Chonghe');
insert into mesto (id_mesto, nazev_mesta) values (946, 'Roma');
insert into mesto (id_mesto, nazev_mesta) values (947, 'Thị Trấn Nguyên Bình');
insert into mesto (id_mesto, nazev_mesta) values (948, 'Jiujiang');
insert into mesto (id_mesto, nazev_mesta) values (949, 'Yinyang');
insert into mesto (id_mesto, nazev_mesta) values (950, 'Gantang');
insert into mesto (id_mesto, nazev_mesta) values (951, 'Yumani');
insert into mesto (id_mesto, nazev_mesta) values (952, 'Darfield');
insert into mesto (id_mesto, nazev_mesta) values (953, 'Arauá');
insert into mesto (id_mesto, nazev_mesta) values (954, 'Las Vegas');
insert into mesto (id_mesto, nazev_mesta) values (955, 'Sagae');
insert into mesto (id_mesto, nazev_mesta) values (956, 'Verkhniy Dashkesan');
insert into mesto (id_mesto, nazev_mesta) values (957, 'Bestöbe');
insert into mesto (id_mesto, nazev_mesta) values (958, 'Ahmadpur Siāl');
insert into mesto (id_mesto, nazev_mesta) values (959, 'Jiaozuo');
insert into mesto (id_mesto, nazev_mesta) values (960, 'Cabo');
insert into mesto (id_mesto, nazev_mesta) values (961, 'Xinsheng');
insert into mesto (id_mesto, nazev_mesta) values (962, 'Przodkowo');
insert into mesto (id_mesto, nazev_mesta) values (963, 'Pimbalayan');
insert into mesto (id_mesto, nazev_mesta) values (964, 'Dar Chabanne');
insert into mesto (id_mesto, nazev_mesta) values (965, 'Kalungu');
insert into mesto (id_mesto, nazev_mesta) values (966, 'Malinaw');
insert into mesto (id_mesto, nazev_mesta) values (967, 'Pámfylla');
insert into mesto (id_mesto, nazev_mesta) values (968, 'Jielin');
insert into mesto (id_mesto, nazev_mesta) values (969, 'Planovskoye');
insert into mesto (id_mesto, nazev_mesta) values (970, 'Meiyuan Xincun');
insert into mesto (id_mesto, nazev_mesta) values (971, 'Claveria');
insert into mesto (id_mesto, nazev_mesta) values (972, 'Palmeira das Missões');
insert into mesto (id_mesto, nazev_mesta) values (973, 'Chifeng');
insert into mesto (id_mesto, nazev_mesta) values (974, 'Randuagung');
insert into mesto (id_mesto, nazev_mesta) values (975, 'Zhongying');
insert into mesto (id_mesto, nazev_mesta) values (976, 'Booterstown');
insert into mesto (id_mesto, nazev_mesta) values (977, 'Los Cerrillos');
insert into mesto (id_mesto, nazev_mesta) values (978, 'Santa Teresa');
insert into mesto (id_mesto, nazev_mesta) values (979, 'Agenebode');
insert into mesto (id_mesto, nazev_mesta) values (980, 'Santa Cecilia');
insert into mesto (id_mesto, nazev_mesta) values (981, 'Al Fashn');
insert into mesto (id_mesto, nazev_mesta) values (982, 'Liusi');
insert into mesto (id_mesto, nazev_mesta) values (983, 'Ciénega');
insert into mesto (id_mesto, nazev_mesta) values (984, 'Afareaitu');
insert into mesto (id_mesto, nazev_mesta) values (985, 'Jambubol');
insert into mesto (id_mesto, nazev_mesta) values (986, 'Kallífytos');
insert into mesto (id_mesto, nazev_mesta) values (987, 'Puyang');
insert into mesto (id_mesto, nazev_mesta) values (988, 'Skulsk');
insert into mesto (id_mesto, nazev_mesta) values (989, 'Uitenhage');
insert into mesto (id_mesto, nazev_mesta) values (990, 'Fria');
insert into mesto (id_mesto, nazev_mesta) values (991, 'Tsengel');
insert into mesto (id_mesto, nazev_mesta) values (992, 'Taihe Chengguanzhen');
insert into mesto (id_mesto, nazev_mesta) values (993, 'Dasi');
insert into mesto (id_mesto, nazev_mesta) values (994, 'Obong');
insert into mesto (id_mesto, nazev_mesta) values (995, 'Lunyuk Ode');
insert into mesto (id_mesto, nazev_mesta) values (996, 'Guanajuato');
insert into mesto (id_mesto, nazev_mesta) values (997, 'Haysyn');
insert into mesto (id_mesto, nazev_mesta) values (998, 'Örebro');
insert into mesto (id_mesto, nazev_mesta) values (999, '5 de Mayo');
insert into mesto (id_mesto, nazev_mesta) values (1000, 'Cipadung');
