CREATE TABLE data(id_plemeno DOUBLE,nazev VARCHAR(10));
INSERT INTO data (id_plemeno,nazev) VALUES 
(1,'Abyssinian'),
(2,'Aegean'),
(3,'American Bobtail'),
(4,'American Curl'),
(5,'Arabian Mau'),
(6,'Asian Indian'),
(7,'Asian Semi-longhair'),
(8,'Australian Mist'),
(9,'Paraguayan'),
(10,'Bambino'),
(11,'Bengal'),
(12,'Brazilian Shorthair'),
(13,'Burmese'),
(14,'Chantilly-Tiffany'),
(15,'Chartreux'),
(16,'Dwelf'),
(17,'Egyptian Mau'),
(18,'European Shorthair'),
(19,'Exotic Shorthair'),
(20,'Foldex'),
(21,'Havana Brown'),
(22,'Highlander'),
(23,'Japanese Bobtail'),
(24,'Kanaani'),
(25,'Khao Manee'),
(26,'Kinkalow'),
(27,'Korat'),
(28,'Korean Bobtail'),
(29,'Lambkin'),
(30,'LaPerm'),
(31,'Maine Coon'),
(32,'Manx'),
(33,'Mekong Bobtail'),
(34,'Minskin'),
(35,'Minuet'),
(36,'Munchkin'),
(37,'Nebelung'),
(38,'Norwegian Forest Cat'),
(39,'Ocicat'),
(40,'Ojos Azules'),
(41,'Oriental Bicolor'),
(42,'Oriental Longhair'),
(43,'Oriental Shorthair'),
(44,'Persian'),
(45,'Persian (traditional)'),
(46,'Peterbald'),
(47,'Pixie-bob'),
(48,'Liebling'),
(49,'Ragdoll'),
(50,'Raas'),
(51,'Russian Blue'),
(52,'Sam Sawet'),
(53,'Siamese'),
(54,'Snowshoe'),
(55,'Sokoke'),
(56,'Tonkinese'),
(57,'Toybob'),
(58,'Toyger'),
(59,'Turkish Angora	'),
(60,'Turkish Van'),
(61,'Turkish Vankedisi'),
(62,'Ukrainian Levkoy'),
(63,'York Chocolate'),
(64,'Thai'),
(65,'Kiowa'),
(66,'Sphynx'),
(67,'Singapura'),
(68,'Siberian'),
(69,'Serengeti'),
(70,'Selkirk Rex');